# Generated by Django 3.1.5 on 2022-05-29 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='passed',
            field=models.BooleanField(default=False, verbose_name='passed'),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='repeat_needed',
            field=models.BooleanField(default=False, verbose_name='repeat_needed'),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='back',
            field=models.TextField(verbose_name='back'),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='front',
            field=models.TextField(verbose_name='front'),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashcards', to='flashcards.set'),
        ),
    ]
